spring:
  application:
    name: expense
  datasource:
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082
